# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1
  - name: Research
    url: publication
    weight: 2
  - name: Teaching
    url: '#teaching'
    weight: 3
  - name: Funding
    url: '#funding'
    weight: 4
  - name: Innovations
    url: project
    weight: 5
  - name: Conferences
    url: conferences
    weight: 6
#  - name: Blog
#    url: post
#    weight: 6
  - name: Contact
    url: '#contact'
    weight: 7
  - name: AI+Econ Lab
    url: lab/
    weight: 8
